### ISSUE TITLE
Unsafe to store verification code in Flask session?

### ISSUE THREAD

**Issue by neilsh** [TwilioDevEd/sms2fa-flask#5]
Is it unsafe to store the verification code in the Flask session? My understanding is that while the session cannot be modified by a user, the signed cookie can still be viewed, even if the user doesn't have access to the Flask.secret_key.

http://flask.pocoo.org/docs/0.11/api/#sessions
https://blog.miguelgrinberg.com/post/how-secure-is-the-flask-user-session

**Comment by dprothero** [comment]
The code itself won't be in the cookie. Also, for security, you will want to access your application using TLS (https) to encrypt the cookie in transit.

**Comment by neilsh** [comment]
@dprothero The problem is, the code actually *is* in the cookie. The two-factor code is stored in the Flask session, and the Flask session is stored in a browser-side cookie. Basically, the tutorial application does the following during signin:

1. if a POST to `/sign_in` has a valid username and password, the user will be redirected to `/confirmation` to confirm the two-factor code
2. the backend generates a random verification code, sends the code out-of-band via SMS using Twilio's API, and saves the code in `flask.session['verification_code']`
3. the user receives the out-of-band verification code and POSTs it via form to the `/confirmation` endpoint. The backend checks if the code the user provided matches the `flask.session['verification_code']`. If the check is successful, we assume the user has access to the physical device that can receive the verification code, and so the user is logged in.

The above would work ok if the session were stored either purely on the backend, or if the session were cryptographically encrypted in a way that prevents the user from reading the `flask.session['verification_code']`. Unfortunately, the Flask session is cryptographically signed, but not cryptographicaly encrypted, so the user is able to trivially decode the session cookie and read its contents. Since the user can easily ready the `flask.session['verification_code']`, even if they don't have access to the physical device receiving the out-of-band SMS code, this completely defeats the purpose of having two-factor authentication.

To quote from the [Flask docs](http://flask.pocoo.org/docs/0.11/api/#sessions) on how `Flask.session` works:

> A session basically makes it possible to remember information from one request to another. The way Flask does this is by using a signed cookie. So the user can look at the session contents, but not modify it unless they know the secret key, so make sure to set that to something complex and unguessable.
