### ISSUE TITLE
Tutorial exposes 2FA code to user

### ISSUE THREAD

**Issue by neilsh** [TwilioDevEd/sms2fa-flask#6]
I'm creating a new issue for this since #5 was closed, so my reply to it might not be visible. It's unsafe to store the 2FA code in the Flask session. Copying my reply from the closed PR:

@dprothero The problem is, the code actually *is* in the cookie. The two-factor code is stored in the Flask session, and the Flask session is stored in a browser-side cookie. Basically, the tutorial application does the following during sign-in:

1. if a POST to `/sign_in` has a valid username and password, the user will be redirected to `/confirmation` to confirm the two-factor code
2. the backend generates a random verification code, sends the code out-of-band via SMS using Twilio's API, and saves the code in `flask.session['verification_code']`
3. the user receives the out-of-band verification code and POSTs it via form to the `/confirmation` endpoint. The backend checks if the code the user provided matches the `flask.session['verification_code']`. If the check is successful, we assume the user has access to the physical device that can receive the verification code, and so the user is logged in.

The above would work ok if the session were stored either purely on the backend, or if the session were cryptographically encrypted in a way that prevents the user from reading the `flask.session['verification_code']`. Unfortunately, the Flask session is cryptographically signed, but not cryptographicaly encrypted, so the user is able to trivially base64-decode the session cookie and read its contents. Since the user can easily read the `flask.session['verification_code']`, even if they don't have access to the physical device receiving the out-of-band SMS code, this completely defeats the purpose of having two-factor authentication.

To quote from the [Flask docs](http://flask.pocoo.org/docs/0.11/api/#sessions) on how `Flask.session` works:

> A session basically makes it possible to remember information from one request to another. The way Flask does this is by using a signed cookie. So the user can look at the session contents, but not modify it unless they know the secret key, so make sure to set that to something complex and unguessable.

Additional reference: https://blog.miguelgrinberg.com/post/how-secure-is-the-flask-user-session

**Comment by dprothero** [comment]
I stand corrected @neilsh. We've immediately updated the README.md with a note on this and will work on fixing this tutorial. Thank you for being persistent!

**Comment by atbaker** [comment]
@neilsh you're absolutely right. Thank you for pointing this out.

I just added a note near the top of the README explaining the vulnerability. I also added a ticket in our internal system to use Flask-Session to address it.

We'd love to hook you up with a Twilio tshirt to thank you for pointing this out. Keep an eye out for an email from @dprothero.
